### ISSUE TITLE
allow additional arguments to ProcessPoolExecutor

### ISSUE THREAD

**Issue by aaronmarkowitz** [florafauna/optimParallel-python#1]
I am running an optimization that uses some unpicklable objects. Because spawned or forked processes require pickling the environment, I would like to supply ProcessPoolExecutor with an initializer function to set up the unpicklable objects independently for each process.

To implement this with optimparallel, I've branched the repo and made the following modifications to optimparallel.py

`parallel_used = {'max_workers': None, 'forward': True, 'verbose': False,
                              'loginfo': False, 'time': False, 'initializer': None,
                              'initargs': (), 'mp_context'=None}`

and

`with concurrent.futures.ProcessPoolExecutor(max_workers=parallel_used.get('max_workers'),
initializer=parallel_used.get('initializer'),
mp_context=parallel_used.get('mp_context'),
initargs=parallel_used.get('initargs')) as executor:`

Would love to see functionality like this added in a future release!

**Comment by florafauna** [comment]
Sounds like a good idea! Would you like to provide an implementation? 
- change python code: `minimize_parallel()` and `fmin_l_bfgs_b_parallel()`
- add unit tests 
- update documentation
- add an example to `example.py`. 

If you provide that, I am happy to mention you has contributor. Otherwise please send me an example use-case and I will see when I'll have time to look into this.

**Comment by aaronmarkowitz** [comment]
Sure, I'm not a developer and haven't really used unit tests, but if I manage it in the next week or so I'll submit a pull request. Thanks!

**Comment by cTatu** [comment]
Hello, this is very interesting. Could be used to pass an MPI Executor as argument? I would want to use this parallel optimization module in a cluster with an executor provided by `mpi4py`
